name: Deploy static content to GitHub Pages
on:
  push:
    branches:
      - main  # Cambia a master si usas master como tu branch principal

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy static site to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .  # Publica los archivos en la raíz del repositorio
